### ISSUE TITLE
uzbl on raspberry pi 2 rendering HD image problem

### ISSUE THREAD

**Issue by navaneetharaopy** [mathstuf/uzbl#17]
Installed UZBL on raspberry pi 2 with this command : ```Sudo apt-get install uzbl```
 
If you are loading local image files(HD images)  Then  image loads part by part(overall image displaying is not smooth). Is it because of my uzbl version? OR is it because number of cores in CPU?   Raspberry pi model B/B+ use ARMv6(single core) and Pi 2 comes with ARMv7(with 4 core).

**Comment by keis** [comment]
In any software version matters it's probably that of webkit which is doing all the rendering etc of uzbl. Does something like epiphany (the gnome webkit browser) load properly?

**Comment by navaneetharaopy** [comment]
Yes, epiphany browser loads HD image properly.

**Comment by mathstuf** [comment]
How is uzbl's next branch? It has a `--bug-info` switch which dumps out useful info as well.
