### ISSUE TITLE
Any developers note 

### ISSUE THREAD

**Issue by navaneetharaopy** [mathstuf/uzbl#18]
Is there any developers note on how to add new features , Folder structure ,Reporting bug, Required packages(compiling in Raspberry pi   needs extra packages) for compiling etc. 

Thank you.

**Comment by keis** [comment]
Hi

First off you probably want uzbl/uzbl rather than this fork.

some general information can be found here https://github.com/uzbl/uzbl/tree/next/docs
and a quick overview of the folder structure is here https://github.com/uzbl/uzbl/blob/next/HACKING.md

**Comment by navaneetharaopy** [comment]
Thank you
